/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * topic.java
 *
 * Created on Jul 8, 2016, 12:05:38 PM
 */
package javaquiz;

import javax.swing.JOptionPane;

/**
 *
 * @author Ideapad
 */
public class topic extends javax.swing.JFrame {

    /** Creates new form topic */
   static  int marks,type,num;
    public topic(int mark,int typ,int num) {
        initComponents();
                prog.setMaximum(80);
           b2.setEnabled(false);
           b3.setEnabled(false);
           b4.setEnabled(false);
           b5.setEnabled(false);
           b6.setEnabled(false);
           b7.setEnabled(false);
           b8.setEnabled(false);
                   
       marks=mark;
           type=typ;
                num=num;
                
               if(num==1)
               {
                   b1.setEnabled(true);
                   
               }
               else if(num==2)
               {
               b1.setEnabled(true);
               b2.setEnabled(true);
                   prog.setValue(10);
               } 
                else if(num==3)
               {
               b1.setEnabled(true);
               b2.setEnabled(true);
               b3.setEnabled(true);
                   prog.setValue(20);
               }
               else if(num==4)
               {
               b1.setEnabled(true);
               b2.setEnabled(true);
               b3.setEnabled(true);
               b4.setEnabled(true);
                   prog.setValue(30);
               }
                  
               else if(num==5)
               {
               b1.setEnabled(true);
               b2.setEnabled(true);
               b3.setEnabled(true);
               b4.setEnabled(true);
               b5.setEnabled(true);
                   prog.setValue(40);
               }
               else if(num==6)
               {
               b1.setEnabled(true);
               b2.setEnabled(true);
               b3.setEnabled(true);
               b4.setEnabled(true);
               b5.setEnabled(true);
               b6.setEnabled(true);
                   prog.setValue(50);
               }
                else if(num==7)
               {
               b1.setEnabled(true);
               b2.setEnabled(true);
               b3.setEnabled(true);
               b4.setEnabled(true);
               b5.setEnabled(true);
               b6.setEnabled(true);
               b7.setEnabled(true);
                   prog.setValue(60);
               }
                else if(num==8)
               {
               b1.setEnabled(true);
               b2.setEnabled(true);
               b3.setEnabled(true);
               b4.setEnabled(true);
               b5.setEnabled(true);
               b6.setEnabled(true);
               b7.setEnabled(true);
               b8.setEnabled(true);
                   prog.setValue(70);
               }
              
               
                   
                
      if(type==1 && marks>=5)
      {
          prog.setValue(10);
          b2.setEnabled(true);
      }
      else if(type==2 && marks>=5)
      {
          prog.setValue(20);
          b3.setEnabled(true);
      }
      else if(type==3 && marks>=5)
      {
          prog.setValue(30);
          b4.setEnabled(true);
      }
      else if(type==4 && marks>=5)
      {
          prog.setValue(40);
          b5.setEnabled(true);
      }
      else if(type==5 && marks>=5)
      {
          prog.setValue(50);
          b6.setEnabled(true);
      }
      else if(type==6 && marks>=5)
      {
          prog.setValue(60);
          b7.setEnabled(true);
      }
      else if(type==7 && marks>=5)
      {
          prog.setValue(70);
          b8.setEnabled(true);
      }
      else if(type==8 && marks>=5)
      {
          prog.setValue(80);
         
      }
      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prog = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(150, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);
        getContentPane().add(prog);
        prog.setBounds(280, 570, 690, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaquiz/quiz/prog2.jpg"))); // NOI18N
        jLabel2.setText("Quiz Progress");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 570, 240, 40);

        b1.setFont(new java.awt.Font("Tahoma", 1, 24));
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaquiz/quiz/basic.jpg"))); // NOI18N
        b1.setText("Basic Concepts");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(350, 20, 290, 70);

        b8.setFont(new java.awt.Font("Tahoma", 1, 24));
        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaquiz/quiz/ds.png"))); // NOI18N
        b8.setText("Data Structures");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8);
        b8.setBounds(350, 460, 300, 80);

        b2.setFont(new java.awt.Font("Tahoma", 1, 24));
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaquiz/quiz/loop.jpg"))); // NOI18N
        b2.setText("Loops");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(30, 120, 260, 80);

        b4.setFont(new java.awt.Font("Tahoma", 1, 24));
        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaquiz/quiz/oop.png"))); // NOI18N
        b4.setText("OOP Concepts");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4);
        b4.setBounds(30, 230, 260, 90);

        b6.setFont(new java.awt.Font("Tahoma", 1, 24));
        b6.setText("Exception Handling");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6);
        b6.setBounds(30, 350, 265, 90);

        b3.setFont(new java.awt.Font("Tahoma", 1, 24));
        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaquiz/quiz/arr.png"))); // NOI18N
        b3.setText("Array,Strings");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(720, 120, 230, 80);

        b5.setFont(new java.awt.Font("Tahoma", 1, 24));
        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaquiz/quiz/thread2.png"))); // NOI18N
        b5.setText("Threading");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(720, 230, 230, 90);

        b7.setFont(new java.awt.Font("Tahoma", 1, 24));
        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaquiz/quiz/gui.jpg"))); // NOI18N
        b7.setText("Applets,GUI");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7);
        b7.setBounds(720, 350, 230, 90);

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 18));
        jButton1.setText("Instructions");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(810, 10, 170, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18));
        jButton2.setText("Sign Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 0, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaquiz/myproject/jl4.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
new ds().setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_b8ActionPerformed

private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
new oop().setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_b4ActionPerformed

private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
new exception().setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_b6ActionPerformed

private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
new thread().setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_b5ActionPerformed

private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
new basic().setVisible(true);

// TODO add your handling code here:
}//GEN-LAST:event_b1ActionPerformed

private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
new loop().setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_b2ActionPerformed

private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
new array().setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_b3ActionPerformed

private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
new gui().setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_b7ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();
new instruction().setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int res=JOptionPane.showConfirmDialog(null, "Are u sure you want to sign out??", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(res==JOptionPane.YES_OPTION)
        {
            this.dispose();
            new login().setVisible(true);
            
        }// TODO add your handling code here:

// TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(topic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(topic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(topic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(topic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new topic(marks,type,num).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar prog;
    // End of variables declaration//GEN-END:variables
}
